volumes:
  sonarqube_data:
  postgresql_data:

networks:
  prodnetwork:
    driver: bridge

services:
  postgresql:
    hostname: postgresql
    container_name: postgresql
    image: bitnami/postgresql
    ports:
      - "32431:5432"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_sonarqube
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=bitnami_sonarqube
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - prodnetwork
  sonar:
    hostname: sonar
    container_name: sonar
    image: bitnami/sonarqube
    ports:
      - "32520:9000"
      - "32521:8443"
    networks:
      - prodnetwork
    volumes:
      - sonarqube_data:/bitnami/sonarqube
    depends_on:
      - postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_PASSWORD=bitnami
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube