FROM python:3-slim AS build
RUN mkdir /app
ADD app.py /app
COPY requirements.txt /
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

FROM gcr.io/distroless/python3
COPY --from=build /app /app
COPY --from=build /usr/local/bin/flask /usr/local/bin/flask
COPY --from=build /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
WORKDIR /app

ENV PYTHONPATH=/usr/local/lib/python3.9/site-packages
#ENTRYPOINT FLASK_APP=/app/app.py /usr/local/bin/flask run --host=0.0.0.0
ENTRYPOINT ["python3","/app/app.py"]
